# Site settings
title: "Zhenxi Blog"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: zhenxi.mi@gmail.com
description: > # this means to ignore newlines until "url:"
  This is Zhenxi, a UI/UX Designer based in NYC. Previoiusly, he worked as a fine artist, advertising AE, and fashion event production executive. Check more at <a href='http://www.zhenximi.me/'>Zhenxi's portfolio</a>.
url: "http://vormwald.github.io" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog/
twitter_username: zhenximi
github_username:  zhenximi

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
